name: 'dbt_test'

config-version: 2
version: '0.21.1'

profile: 'dbt-test'

macro-paths: ["macros"]
source-paths: ["models"]

# target-path: "target"
# clean-targets:
#     - "target"
#     - "dbt_modules"
#     - "logs"

# require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt-test:
      materialized: table
      staging:
        materialized: view