name: 'dbt_test'

config-version: 2
version: '0.21.1'

profile: 'dbt-test'

macro-paths: ["macros"]
source-paths: ["models"]

# target-path: "target"
# clean-targets:
#     - "target"
#     - "dbt_modules"
#     - "logs"

# require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  dbt-test:
      materialized: table
      staging:
        materialized: view

on-run-end: "FOR row IN
      SELECT table_schema, table_name
      FROM information_schema.tables
      WHERE table_type = 'BASE TABLE'
      AND table_schema = 'cms_synthetic_patient_data_omop'
      AND table_name ILIKE ('_airbyte' || '%')
   LOOP
      EXECUTE 'DROP TABLE ' || quote_ident(row.table_schema) || '.' || quote_ident(row.table_name) || ' CASCADE';
      RAISE INFO 'Dropped tables: %', quote_ident(row.table_schema) || '.' || quote_ident(row.table_name);
   END LOOP;"